# Generated by Django 4.1.7 on 2023-05-01 09:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Trang cung cấp thông tin')),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stock_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROE', models.FloatField(default=0, null=True, verbose_name='Return on Equity - Lợi nhuận trên tổng số vốn chủ sở hữu')),
                ('ROA', models.FloatField(default=0, null=True, verbose_name='Return on assets - Lợi nhuận trên tổng tài sản doanh nghiệp')),
                ('EPS', models.FloatField(default=0, null=True, verbose_name='Earnings per share - Lợi nhuận trên cổ phiếu')),
                ('PA', models.FloatField(default=0, null=True, verbose_name='Price to Assets - Giá trị trên tài sản')),
                ('PE', models.FloatField(default=0, null=True, verbose_name='Price to Earnings - Giá trị trên thu nhập')),
                ('provider', models.ForeignKey(default='FBC', on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='cryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_key', models.TextField()),
                ('pri_key', models.TextField()),
                ('live_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='propertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=datetime.datetime.now)),
                ('cash', models.FloatField(default=0, verbose_name='Tiền mặt, vàng, bạc')),
                ('deposit', models.FloatField(default=0, verbose_name='Tiền gửi tại ngân hàng nhà nước')),
                ('loan_credit_institutions', models.FloatField(default=0, verbose_name='Cho vay các tổ chức tín dụng')),
                ('loan_customer', models.FloatField(default=0, verbose_name='Cho vay khách hàng')),
                ('total', models.FloatField(default=0, verbose_name='Tổng tài sản')),
                ('provider', models.ForeignKey(default='FBC', on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
            options={
                'ordering': ['stock'],
                'unique_together': {('stock', 'year', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=datetime.datetime.now)),
                ('NPL', models.FloatField(default=0, null=True, verbose_name='Non-Performing Loan - Nợ Xấu')),
                ('LEV', models.FloatField(default=0, null=True, verbose_name='Leverage - Tỷ lệ nợ')),
                ('provider', models.ForeignKey(default='FBC', on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
            options={
                'ordering': ['stock'],
                'unique_together': {('stock', 'year', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=datetime.datetime.now)),
                ('net_interest_income', models.FloatField(default=0, verbose_name='Lãi thuần')),
                ('interest_income', models.FloatField(default=0, verbose_name='Lãi')),
                ('service_activities', models.FloatField(default=0, verbose_name='Lợi nhuận từ hoạt động dịch vụ')),
                ('other_activities', models.FloatField(default=0, verbose_name='Lợi nhuận từ hoạt động khác')),
                ('profit_after_tax', models.FloatField(default=0, verbose_name='Lợi nhuận sau thuế')),
                ('provider', models.ForeignKey(default='FBC', on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
            options={
                'ordering': ['stock'],
                'unique_together': {('stock', 'year', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=datetime.datetime.now)),
                ('bad_debt', models.FloatField(default=0, verbose_name='Nợ xấu')),
                ('total_debt', models.FloatField(default=0, verbose_name='Dư nợ')),
                ('provider', models.ForeignKey(default='FBC', on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
            options={
                'ordering': ['stock'],
                'unique_together': {('stock', 'year', 'provider')},
            },
        ),
    ]
